a=int(input("enter first number:"))
b=int(input("enter second number:"))
print("***********comparison operators************")
print("is equal:",a==b)
print("is not equal:",a!=b)
print("Greater than:",a>b)
print("Less than:",a<b)
print("lessthan equal:",a<=b)
print("greater than equal:",a>=b)
